In [33]:
# Class: COEN 140 Lab Machine Learning/Data Mining
# Name: Matthew Davenport
# Date: 9/25/2022
# Title: Lab 9 – Dimensionality Reduction

import numpy as np
import math

In [34]:
import pickle
from sklearn.datasets import fetch_openml

try: 
    with open("data.pickle", "rb") as fp:
        X_training = pickle.load(fp)
    print("File unpickled successfully")

except FileNotFoundError:
    mnist = fetch_openml('mnist_784', version=1)
    X_training = mnist["data"][:2000]
    
    with open("data.pickle", "wb") as fp:
        pickle.dump(X_training, fp)

print(X_training.shape)

File unpickled successfully
(2000, 784)


Centering Data for PCA

In [39]:
data = np.asarray(X_training)
print("Data shape: ",data.shape)

data_size = len(data)
print("Data size: ",data_size)
means = np.zeros(data_size)
print("Means shape: ", means.shape)

for i in range(data_size):
    means[i] = np.mean(data[i])

centered_data = np.zeros((data_size, len(data[0])))
print("centered_data shape: ",centered_data.shape)
print("Means: ", means)
print(len(data[0]))
for i in range(data_size):
    for j in range(len(data[i])):
        centered_data[i][j] = data[i][j] - means[i]
        
print(centered_data)

means_check = np.zeros(data_size)
for i in range(data_size):
    means_check[i] = np.mean(centered_data[i])

zeros = np.zeros(data_size)
if np.array_equal(means_check, zeros, equal_nan=True):
    print("Data centered successfully")
else:
    print(means_check)

print(data)

centered_data_cov = np.cov(centered_data)
print(centered_data_cov.shape)


Data shape:  (2000, 784)
Data size:  2000
Means shape:  (2000,)
centered_data shape:  (2000, 784)
Means:  [35.10841837 39.6619898  24.7997449  ... 54.42729592 27.80994898
 77.75765306]
784
[[-35.10841837 -35.10841837 -35.10841837 ... -35.10841837 -35.10841837
  -35.10841837]
 [-39.6619898  -39.6619898  -39.6619898  ... -39.6619898  -39.6619898
  -39.6619898 ]
 [-24.7997449  -24.7997449  -24.7997449  ... -24.7997449  -24.7997449
  -24.7997449 ]
 ...
 [-54.42729592 -54.42729592 -54.42729592 ... -54.42729592 -54.42729592
  -54.42729592]
 [-27.80994898 -27.80994898 -27.80994898 ... -27.80994898 -27.80994898
  -27.80994898]
 [-77.75765306 -77.75765306 -77.75765306 ... -77.75765306 -77.75765306
  -77.75765306]]
[ 6.67040119e-15 -2.90017443e-15  2.90017443e-15 ... -2.32013955e-15
  1.16006977e-15  8.12048841e-15]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]
(2000, 2000)
